# Generated by Django 2.0.13 on 2019-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='text',
        ),
        migrations.RemoveField(
            model_name='component',
            name='title',
        ),
        migrations.AddField(
            model_name='component',
            name='download_URL',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='homepage_URL',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='license',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='primary_language',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='version',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
